Added Expense Tracker mini js project
rudra016/WebDev-OpenSource pull request #317
Opened 2023-10-29 11:14 UTC by urwah1248

### About the Expense Tracker

Simple UI with Balance, Expenses and Income as analytics. Simple form to add a transaction which updates the total transactions and saves in localstorage.

2023-10-30 14:00 UTC, Haris-Mohanty requested changes
Hi @urwah1248, add some screenshots!

2023-10-30 15:34 UTC, urwah1248 commented
Hi @Haris-Mohanty, Screenshots have been added

2023-10-30 15:58 UTC, Haris-Mohanty approved these changes

2023-10-31 15:43 UTC, urwah1248 commented
@Haris-Mohanty It got approved but it isn't merged yet.

2023-10-31 18:02 UTC, merged